# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611f8e9cbd32d686f32d0ef53f041193660863047ee261cdebdf58bde12aa1e06ab65c440b2e0cc93b51da8afadc85ff4d04c3816520212e2bc2047ead7cc334

test:
  secret_key_base: 5d1004a8b3b4ccccf3fcf08792f2af2513e1ab6a5ad89142ec80fc599146e4b1c75ddff8dda350fc29b543623f2e65cfff4b5c1544027dd9489f6967be6bdaa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
